### ISSUE TITLE
PHPCS usage

### ISSUE THREAD

**Issue by Chrico** [inpsyde/boilerplate#11]
The current implementation of PHPCS is kind of "complex" and can be done way easier without triggering the complete script ` "phpcs": "\"vendor/bin/phpcs\" --config-set installed_paths vendor/wp-coding-standards/wpcs"` by adding the "standard".

In MultilingualPress and Inpsyde Google Tag Manager we're using the `dealerdirect/phpcodesniffer-composer-installer`-Package which automatically installs all via composer required coding standards. This way we only need to trigger `"phpcs": "\"vendor/bin/phpcs\"` in our script.

**Comment by dnaber-de** [comment]
@Chrico 
The boilerplate now drops a `phpcs.xml.dist` file with the content:
```
<?xml version="1.0" ?>
<ruleset name="Inpsde Coding Standard">
	<rule ref="Inpsyde"/>
	<file>./src</file>
</ruleset>
```

`inpsyde/php-coding-standards` is now required with `@stable` stability constraint to make sure it always fetches the lates stable release regardless of any `minimum-stability` settings of the actual package.

Also, I removed the phpcs scripts from any Composer install events and replaced it with a simple shortcut:
```
    "scripts": {
        "ci": [
            "vendor/bin/phpcs",
        ]
    }
```

What do you think?

**Comment by Chrico** [comment]
Looks good for me! :-)

**Comment by dnaber-de** [comment]
You didn't look thoroughly 😄
