### ISSUE TITLE
License name for GPL-licensed code.

### ISSUE THREAD

**Issue by tzimpel** [inpsyde/boilerplate#22]
The composer.json need a explizit string: GPL-2.0-or-later
Inside the plugin comment for WordPress you must use: GPLv2+

**Comment by bueltge** [comment]
We should also remove the MIT License Template (_templates/LICENSE.mit.template), so we write all plugins, themes, etc. for WP always under GPL2v+
Thats include also the removal of the option to set a license - https://github.com/inpsyde/boilerplate/blob/f3bb30c3c7b8f5862f8bade587a475f042cf1b2b/_config/defaults.php#L58

**Comment by dugajean** [comment]
@bueltge What about plugin authors outside of Inpsyde who use this package? Maybe they wish to continue using MIT? (Considering this package is open source)

**Comment by bueltge** [comment]
Good point and good simple solution. However also other authors should use GPLv2, is more secure in context of WP usage. However not our topic.

**Comment by cliffordp** [comment]
WordPress stuff needs to be _compatible_ with GPL, which MIT is -- technically called the "Expat" license by GPL itself:
* https://www.gnu.org/licenses/license-list.en.html#SoftwareLicenses
* https://en.wikipedia.org/wiki/MIT_License#Variants

**Comment by dnaber-de** [comment]
@bueltge 
> We should also remove the MIT License Template (_templates/LICENSE.mit.template), so we write all plugins, themes, etc. for WP always under GPL2v+
We can set GPL to the default but I wouldn't remove MIT as we do have packages that don't have to do anything with WordPress

**Comment by bueltge** [comment]
If we have packages, results there have no depending to WP, so it is fine that we leave the MIT, because we use MIT for solutions without a dependency to WP.

**Comment by bueltge** [comment]
If we have packages, results there have no depending to WP, so it is fine that we leave the MIT, because we use MIT for solutions without a dependency to WP.

**Comment by bueltge** [comment]
Should fixed with #25 - right GPL string and also the possibility to use MIT.
