### ISSUE TITLE
PSR Rule File, Namespace, class?

### ISSUE THREAD

**Issue by bueltge** [inpsyde/boilerplate#7]
The setup ask for a namespace, like `InpsydePlugin`, but the file name is `inpsyde-plugin.php`. I think we should run in the [PSR 0](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md) rules, so we worm more and more in this context of PSR in other libraries.
Your opinions?

**Comment by dnaber-de** [comment]
I don't get the point. The name of the plugin file is not relevant for PSR autoloading. Instead, every file inside the `src` should follow the PRS-4 (PSR-0 is deprecaded) naming conventions.

**Comment by bueltge** [comment]
Yes. Is not necessary for the plugin-root-file. If we have it for the files inside `src` so it is ok for me.
